{ config, lib, ... }:

with lib;

let
  cfg = config.system-manager.pam;

  # Detect OS to select the correct auth include
  # This tries to read /etc/os-release during evaluation to dynamically configure PAM
  # based on whether the system is Arch-based, Debian-based, etc.
  osRelease = if builtins.pathExists "/etc/os-release" then builtins.readFile "/etc/os-release" else "";

  isDebianOrUbuntu = builtins.match ".*ID(_LIKE)?=(debian|ubuntu).*" osRelease != null;
  isArch = builtins.match ".*ID(_LIKE)?=(arch|cachyos).*" osRelease != null;
  isFedora = builtins.match ".*ID(_LIKE)?=(fedora).*" osRelease != null;

  authInclude =
    if cfg.authInclude != null then cfg.authInclude
    else if isDebianOrUbuntu then "common-auth"
    else if isArch then "system-auth"
    else if isFedora then "system-auth"
    else "system-auth"; # Fallback assuming system-auth is the most common default

  accountInclude =
    if isDebianOrUbuntu then "common-account"
    else if isArch then "system-auth"
    else if isFedora then "system-auth"
    else "system-auth";

  passwordInclude =
    if isDebianOrUbuntu then "common-password"
    else if isArch then "system-auth"
    else if isFedora then "system-auth"
    else "system-auth";

  sessionInclude =
    if isDebianOrUbuntu then "common-session"
    else if isArch then "system-auth"
    else if isFedora then "system-auth"
    else "system-auth";

  pamConfigText = ''
    # PAM configuration generated by system-manager
    auth include ${authInclude}
    account include ${accountInclude}
    password include ${passwordInclude}
    session include ${sessionInclude}
  '';

in
{
  options.system-manager.pam = {
    enable = mkEnableOption "Configure PAM for non-NixOS via system-manager";

    services = mkOption {
      type = types.listOf types.str;
      default = [ ];
      example = [ "hyprlock" "swaylock" ];
      description = ''
        List of PAM services to create in /etc/pam.d/.
        For example, adding "hyprlock" creates /etc/pam.d/hyprlock.
      '';
    };

    authInclude = mkOption {
      type = types.nullOr types.str;
      default = null;
      description = ''
        Override the detected PAM auth include file.
        Useful if OS detection fails or a specific file is needed.
      '';
    };
  };

  config = mkIf cfg.enable {
    environment.etc = lib.genAttrs (map (name: "pam.d/${name}") cfg.services) (_name: {
      text = pamConfigText;
      mode = "0644";
    });
  };
}
