name: Pull Request Build

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Add your build or test steps here
    - name: Run your build/test
      run: echo "Running build or tests" # Replace with actual commands

    - name: Check build result
      if: ${{ failure() }}
      run: |
        echo "Build failed, closing pull request"
        gh pr close ${{ github.event.pull_request.number }} -R ${{ github.repository }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Merge on success
      if: ${{ success() }}
      run: |
        echo "Build succeeded, merging pull request"
        gh pr merge ${{ github.event.pull_request.number }} --rebase -R ${{ github.repository }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
