pull_request_rules:
  - name: "Merge when all checks pass"
    conditions:
      # Check if the required GitHub Actions workflows have succeeded
      - "status-success=flake_deadnix"
      - "status-success=flake_check"
      - "status-success=flake_format"
    actions:
      merge:
        method: rebase

  - name: "Close if any checks fail"
    conditions:
      # Check if any of the required GitHub Actions workflows have failed
      - "status-failure=flake_deadnix"
      - "status-failure=flake_check"
      - "status-failure=flake_format"
    actions:
      close:
        message: "Closing this pull request as one or more checks failed."
