pull_request_rules:
  - name: Merge flake
    description: Merge when PR passes all branch protection during office hours
    conditions:
      - check-failure!=flake_check
    actions:
      close:
  - name: Merge flake
    description: Merge when PR passes all branch protection during office hours
    conditions:
      - check-success = flake_check
    actions:
      merge:
