site_name: My Nix Config
site_url: https://rishabh5321.github.io/dotfiles/
theme:
  name: material
  palette:
    - scheme: slate
      primary: deep purple
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - About: about.md
  - Contact: contact.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
