# WARNING : This file was generated by README.org
# DO NOT MODIFY THIS FILE!
# Any changes made here will be overwritten.
{
  programs.waybar = {
    enable = true;
    settings = {
      mainBar = {
        layer = "top";
        height = 24;
        modules-left = [ "hyprland/workspaces" ];
        modules-center = [ "hyprland/window" ];
        modules-right = [
          "idle_inhibitor"
          "pulseaudio"
          "network"
          "cpu"
          "memory"
          "temperature"
          "clock"
          "tray"
          "battery"
        ];
        "idle_inhibitor" = {
          format = "{icon}";
          format-icons = {
            activated = "󰒳";
            deactivated = "󰒲";
          };
        };
        "network".format = "{ipaddr}";
        "cpu".tooltip = false;
        "temperature".tooltip = false;
        "tray".spacing = 10;
      };
    };
    style = ''
      * {
        font-family: Iosevka Nerd Font, Roboto, Helvetica, Arial, sans-serif;
        font-size: 13px;
      }

      window#waybar {
        background-color: #4c566a;
        color: #ffffff;
        transition-property: background-color;
        border-bottom: 0px solid rgba(0, 0, 0, 0);
        transition-duration: .5s;
      }

      #workspaces button {
        padding: 0 5px;
        background-color: transparent;
        border: none;
        border-radius: 0;
      }

      #workspaces button:hover {
        background: #2e3440;
        color: white;
      }

      #workspaces button.active {
        background-color: #5e81ac;
        box-shadow: inset 0 -3px #ffffff;
      }

      #clock,
      #idle_inhibitor
      #battery,
      #cpu,
      #memory,
      #temperature,
      #network,
      #pulseaudio,
      #tray {
        padding: 0 10px;
        background-color: transparent;
      }

      #window,
      #workspaces {
        margin: 0 4px;
      }

      .modules-left > widget:first-child > #workspaces {
        margin-left: 0;
      }

      .modules-right > widget:last-child > #workspaces {
        margin-right: 0;
      }

      #battery.charging, #battery.plugged {
        color: #ffffff;
        background-color: #26A65B;
      }

      #network.disconnected {
        background-color: #f53c3c;
      }

      #temperature.critical {
        background-color: #eb4d4b;
      }
    '';
  };
}
