name: Build and Upload to Cachix

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Install Cachix and jq
        run: |
          nix profile install nixpkgs#cachix
          nix profile install nixpkgs#jq

      - name: Build NixOS Configurations
        run: |
          CONFIGURATIONS=$(nix flake metadata . | jq -r ".outputs.nixosConfigurations | keys[]")
          for CONFIGURATION in $CONFIGURATIONS; do
            echo "Building configuration: $CONFIGURATION"
            nix build ".#nixosConfigurations.$CONFIGURATION.config.system.build.toplevel"
          done

      - name: Upload to Cachix
        run: cachix push "your-cache-name" $(nix store path-info --all --recursive result) --token "${{ secrets.CACHIX_AUTH_TOKEN }}"
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}