name: Build and Push to Cachix

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CACHIX_NAME: "prebuild-pkgs"    
  SYSTEM: "x86_64-linux"          

jobs:
  setup-cachix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
          substituters = https://cache.nixos.org https://${{ env.CACHIX_NAME }}.cachix.org
          trusted-public-keys = prebuild-pkgs.cachix.org-1:s/ghpCBw/JYgqD++qyRktRzM3Up9rZaDk904xvfv51E= ${{ secrets.CACHIX_PUBLIC_KEY }}

    - uses: cachix/cachix-action@v14
      with:
        name: ${{ env.CACHIX_NAME }}
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

  build-and-push:
    needs: setup-cachix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host: ["redmi", "dell"]  # Your host configurations from flake.nix
    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Build and push system configuration
      run: |
        nix build .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel --json \
          | jq -r '.[].outputs[]' \
          | cachix push ${{ env.CACHIX_NAME }}