name: Build and Push Minimal Configs to Cachix

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CACHIX_NAME: "prebuild-pkgs"
  SYSTEM: "x86_64-linux"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix (minimal)
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-24-11
          extra_nix_config: |
            experimental-features = nix-command flakes
            auto-optimise-store = true
            keep-outputs = false
            keep-derivations = false

      - name: Install Cachix
        run: nix profile install nixpkgs#cachix

      - name: Authenticate Cachix
        run: cachix authtoken ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Free disk space (aggressive)
        run: |
          sudo rm -rf /usr/local/lib/android /usr/share/dotnet /opt/ghc /usr/local/share/boost /swapfile
          sudo apt-get clean
          df -h

      - name: Build and push redmi (minimal)
        run: |
          # Build with minimal dependencies
          nix build .#nixosConfigurations.redmi.config.system.build.toplevel \
            --option sandbox false \
            --option warn-dirty false \
            --print-build-logs
          
          # Push only essential paths
          nix-store -qR --include-outputs $(readlink -f result) | sort -u > paths-to-push.txt
          cachix push ${{ env.CACHIX_NAME }} -j4 < paths-to-push.txt || echo "Some paths failed to push"
          
          # Aggressive cleanup
          rm -rf result paths-to-push.txt
          nix-collect-garbage --delete-old
          nix store gc

      - name: Intermediate cleanup
        run: |
          nix-collect-garbage --delete-old
          nix store gc
          df -h

      - name: Build and push dell (minimal)
        run: |
          # Build with minimal dependencies
          nix build .#nixosConfigurations.dell.config.system.build.toplevel \
            --option sandbox false \
            --option warn-dirty false \
            --print-build-logs
          
          # Push only essential paths
          nix-store -qR --include-outputs $(readlink -f result) | sort -u > paths-to-push.txt
          cachix push ${{ env.CACHIX_NAME }} -j4 < paths-to-push.txt || echo "Some paths failed to push"
          
          # Final cleanup
          rm -rf result paths-to-push.txt
          nix-collect-garbage --delete-old
          nix store gc
          df -h