name: Build and Push to Cachix

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CACHIX_NAME: "prebuild-pkgs"    
  SYSTEM: "x86_64-linux"          

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
          substituters = https://${{ env.CACHIX_NAME }}.cachix.org https://cache.nixos.org
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0niz+iQsNJlWhRM4tG/2aK+YRDjYTU= cachix.cachix.org-1:Kq8rLSmFVD2UMl3EsjEAXP6J08QbEINa6Zx7RirzOJc=

    - name: Install Cachix
      run: nix-env -iA nixpkgs.cachix

    - name: Authenticate Cachix
      run: cachix authtoken ${{ secrets.CACHIX_AUTH_TOKEN }}

  build-and-push:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host: ["redmi", "dell"]  # Your host configurations from flake.nix
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Install Cachix
      run: nix-env -iA nixpkgs.cachix

    - name: Authenticate Cachix
      run: cachix authtoken ${{ secrets.CACHIX_AUTH_TOKEN }}

    - name: Build and push system configuration
      run: |
        nix build .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel --json \
          | jq -r '.[].outputs[]' \
          | cachix push ${{ env.CACHIX_NAME }}
