name: "Cleanup Old Workflow Runs"
concurrency: "cleanup-workflow"  # Prevents overlapping runs
permissions:
  contents: write
  pull-requests: write
  actions: write # Add this line
  
on:
  schedule:
    - cron: "0 0 * * *"  
  workflow_dispatch:  # Allow manual triggers

jobs:
  cleanup:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main  # Ensures the latest version of the script is used

      - name: Install Nix (with Cachix support)
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            extra-substituters = https://colemickens.cachix.org https://nixpkgs-wayland.cachix.org
            extra-trusted-public-keys = nixpkgs-wayland.cachix.org-1:3lwxaILxMRkVhehr5StQprHdEo4IrE8sRho9R9HOLYA= colemickens.cachix.org-1:bNrJ6FfMREB4bd4BOjEN85Niu8VcPdQe4F4KxVsb/I4=

      - name: Install Nushell (if needed)
        run: |
          nix profile install nixpkgs#nushell  # Installs Nushell via Nix

      - name: Run Cleanup Script
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}  # Auto-resolves to current repo
          GH_TOKEN: ${{ github.token }}  # Required for GitHub API access
        run: |
          chmod +x ./scripts/clean_actions.nu  # Ensure executable
          nu ./scripts/clean_actions.nu  # Execute the Nushell script