name: flake-check
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  flake-checks:
    name: Flake Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          install_url: https://nixos.org/nix/install
          extra_nix_config: |
            auto-optimise-store = true
            experimental-features = nix-command flakes
            download-buffer-size = 500000000
      - name: Setup Cachix
        uses: cachix/cachix-action@v16
        with:
          name: buildcache
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          pushFilter: ".*"
      - name: Run Flake Check
        id: flake_check
        run: |
          nix flake check 2>&1 | tee flake_check.log
          if grep -E "(warning:|error:)" flake_check.log > flake_check_filtered.log; then
            echo "has_issues=true" >> $GITHUB_OUTPUT
            echo "FLAKE_STATUS=failed" >> $GITHUB_ENV
            exit 1
          else
            echo "No warnings or errors." > flake_check_filtered.log
            echo "has_issues=false" >> $GITHUB_OUTPUT
            echo "FLAKE_STATUS=passed" >> $GITHUB_ENV
          fi
      - name: Check NixOS Configuration
        id: build
        if: always() # Run even if flake check fails
        run: |
          if nix build .#nixosConfigurations.dell.config.system.build.toplevel 2>&1 | tee build.log; then
            echo "BUILD_STATUS=passed" >> $GITHUB_ENV
            echo "NixOS configuration check completed successfully" > build_filtered.log
          else
            echo "BUILD_STATUS=failed" >> $GITHUB_ENV
            cat build.log > build_filtered.log
          fi
      - name: Debug Logs
        run: |
          echo "--- Flake Check Results ---"
          cat flake_check_filtered.log
          echo "--- Build Results ---"
          cat build_filtered.log
      - name: Send Telegram Notification
        if: always()
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          BRANCH_NAME="${{ github.ref_name }}"
          REPO_NAME="${{ github.repository }}"
          FLAKE_STATUS="${{ env.FLAKE_STATUS }}"
          BUILD_STATUS="${{ env.BUILD_STATUS }}"
          
          # Define combined status message
          if [[ "$FLAKE_STATUS" == "passed" && "$BUILD_STATUS" == "passed" ]]; then
            STATUS_MESSAGE="✅ Checks for $REPO_NAME passed on branch $BRANCH_NAME."
          else
            STATUS_MESSAGE="❌ Checks for $REPO_NAME failed on branch $BRANCH_NAME.%0ACheck GitHub Actions for details."
          fi
          
          # Process warnings and errors
          MESSAGE="Flake Check: $FLAKE_STATUS%0ABuild: $BUILD_STATUS%0A%0A"
          
          if [ -s flake_check_filtered.log ]; then
            FLAKE_WARNINGS=$(awk '{print NR". "$0}' flake_check_filtered.log | head -10 | perl -pe 's/\n/%0A/g')
            MESSAGE+="Flake Check Issues:%0A\`\`\`%0A$FLAKE_WARNINGS%0A\`\`\`%0A%0A"
          fi
          
          if [ -s build_filtered.log ] && [ "$BUILD_STATUS" == "failed" ]; then
            BUILD_ERRORS=$(awk '{print NR". "$0}' build_filtered.log | head -10 | perl -pe 's/\n/%0A/g')
            MESSAGE+="Build Issues:%0A\`\`\`%0A$BUILD_ERRORS%0A\`\`\`"
          fi
          
          # Send message to Telegram
          curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage" \
            -d "chat_id=$CHAT_ID" \
            -d "text=$STATUS_MESSAGE%0A%0A$MESSAGE%0A%0AGenerated on $(TZ='Asia/Kolkata' date)" \
            -d "parse_mode=Markdown"