name: flake_format

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags-ignore:
      - 'update'
  schedule:
    - cron: '0 */12 * * *'

jobs:
  nix-format-lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v30
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Install Nix Linting and Formatting Tools
      run: |
        nix-channel --update
        nix-env -i statix nixpkgs-fmt -f '<nixpkgs>'
      env:
        NIX_PATH: nixpkgs=channel:nixos-unstable

    - name: Run Statix Lint
      run: statix fix

    - name: Run Nix Format
      run: nixpkgs-fmt .
    
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: 'chore: auto lint and format'