name: flake-check
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  flake-checks:
    name: Flake Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          install_url: https://nixos.org/nix/install
          extra_nix_config: |
            auto-optimise-store = true
            experimental-features = nix-command flakes
            download-buffer-size = 500000000

      - name: Setup Cachix
        uses: cachix/cachix-action@v14
        with:
          name: buildcache  # Corrected cache name to "buildcache" (no hyphen)
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          pushFilter: ".*"  # Configure which store paths to push (default is all)

      - name: Run Flake Check
        id: flake_check
        run: |
          nix flake check 2>&1 | tee flake_check.log
          if grep -E "(warning:|error:)" flake_check.log > flake_check_filtered.log; then
            echo "has_issues=true" >> $GITHUB_OUTPUT
            echo "FLAKE_STATUS=failed" >> $GITHUB_ENV
            exit 1
          else
            echo "No warnings or errors." > flake_check_filtered.log
            echo "has_issues=false" >> $GITHUB_OUTPUT
            echo "FLAKE_STATUS=passed" >> $GITHUB_ENV
          fi

      - name: Debug Logs
        run: cat flake_check_filtered.log

      - name: Send Telegram Notification
        if: always()
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          BRANCH_NAME="${{ github.ref_name }}"
          REPO_NAME="${{ github.repository }}"
          FLAKE_STATUS="${{ env.FLAKE_STATUS }}"

          # Define status message based on our own status variable
          if [[ "$FLAKE_STATUS" == "passed" ]]; then
            STATUS_MESSAGE="✅ Flake check for $REPO_NAME passed on branch $BRANCH_NAME."
          else
            STATUS_MESSAGE="❌ Flake check for $REPO_NAME failed on branch $BRANCH_NAME.%0ACheck GitHub Actions for details."
          fi

          # Process warnings and errors
          if [ -s flake_check_filtered.log ]; then
            WARNINGS=$(awk '{print NR". "$0}' flake_check_filtered.log | head -15 | perl -pe 's/\n/%0A/g')  # Limit to 15 lines
            MESSAGE="Flake Check Results:%0A\`\`\`%0A$WARNINGS%0A\`\`\`"
          else
            MESSAGE="No warnings or errors found."
          fi

          # Send message to Telegram
          curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage" \
            -d "chat_id=$CHAT_ID" \
            -d "text=$STATUS_MESSAGE%0A%0A$MESSAGE%0A%0AGenerated on $(TZ='Asia/Kolkata' date)" \
            -d "parse_mode=Markdown"