name: flake_check

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  flake-checks:
    name: flake_check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          install_url: https://nixos.org/nix/install
          extra_nix_config: |
            auto-optimise-store = true
            experimental-features = nix-command flakes

      - name: flake_check
        run: nix flake check

        
      - name: Send Telegram Notification
        if: always()
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          BRANCH_NAME="${{ github.ref_name }}"
          if [[ "${{ job.status }}" == "success" ]]; then
            MESSAGE="✅ Flake check for Rishabh5321/dotfiles completed successfully on branch $BRANCH_NAME."
          else
            MESSAGE="❌ Flake check for Rishabh5321/dotfiles failed on branch $BRANCH_NAME. Check GitHub Actions for details."
          fi
          curl -s -X POST https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage \
            -d chat_id=$CHAT_ID \
            -d text="$MESSAGE"