name: Dead code analysis
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    tags-ignore:
      - 'update'
jobs:
  deadnix:
    name: Deadnix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v15
        with:
          name: deadnix
      - uses: astro/deadnix-action@main
        with:
          commit_message: 'chore: remove dead code'