name: flake-check
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  flake-checks:
    name: Flake Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          install_url: https://nixos.org/nix/install
          extra_nix_config: |
            auto-optimise-store = true
            experimental-features = nix-command flakes
            download-buffer-size = 500000000

      - name: Run Flake Check
        id: flake_check
        run: |
          # Run flake check and log output
          nix flake check 2>&1 | tee flake_check.log || FLake_CHECK_FAILED=$?

          # Filter warnings and errors
          grep -E "(warning:|error:)" flake_check.log > flake_check_filtered.log || true

          # If flake check failed, check if it's due to actual errors
          if [ -n "$FLake_CHECK_FAILED" ]; then
            if [ -s flake_check_filtered.log ]; then
              echo "Errors or warnings found. Failing the step."
              exit 1
            else
              echo "Flake check failed, but no errors or warnings were found in the log."
              echo "This might be due to a non-error-related failure (e.g., network issues)."
              exit 0  # Allow the job to pass
            fi
          else
            echo "Flake check passed successfully."
          fi

      - name: Debug Logs
        run: |
          echo "=== Full Flake Check Log ==="
          cat flake_check.log
          echo "=== Filtered Log (Warnings/Errors) ==="
          cat flake_check_filtered.log

      - name: Send Telegram Notification
        if: failure()
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          BRANCH_NAME="${{ github.ref_name }}"
          REPO_NAME="${{ github.repository }}"
          STATUS="${{ job.status }}"

          # Define status message
          STATUS_MESSAGE="❌ Flake check for $REPO_NAME failed on branch $BRANCH_NAME.%0ACheck GitHub Actions for details."

          # Process warnings and errors
          if [ -s flake_check_filtered.log ]; then
            WARNINGS=$(awk '{print NR". "$0}' flake_check_filtered.log | head -15 | perl -pe 's/\n/%0A/g')  # Limit to 15 lines
            MESSAGE="Flake Check Results:%0A\`\`\`%0A$WARNINGS%0A\`\`\`"
          else
            MESSAGE="Flake check failed, but no errors or warnings were found in the log."
          fi

          # Send message to Telegram
          curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage" \
            -d "chat_id=$CHAT_ID" \
            -d "text=$STATUS_MESSAGE%0A%0A$MESSAGE%0A%0AGenerated on $(TZ='Asia/Kolkata' date)" \
            -d "parse_mode=Markdown"