name: Build NixOS configs and push to Cachix

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build disk space
        uses: easimon/maximize-build-space@v10

      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v26
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - uses: cachix/cachix-action@v12
        with:
          name: rishabh5321
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build NixOS Configurations
        run: |
          nix build .#nixosConfigurations.redmi.config.system.build.toplevel --no-link
          #nix build .#nixosConfigurations.dell.config.system.build.toplevel --no-link
