name: Build NixOS configs and push to Cachix

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build disk space (enhanced)
        uses: easimon/maximize-build-space@v10
        with:
          root-reserve-mb: 512  # Reduced from 1024 to free more space
          swap-size-mb: 4096   # Increased swap for Nix builds
          remove-dotnet: 'true'
          remove-android: 'true'  # Additional space saving
          remove-haskell: 'true'  # Additional space saving

      - uses: actions/checkout@v4

      - name: Install Nix (Single-User)
        uses: cachix/install-nix-action@v31
        with:
          install_url: https://nixos.org/nix/install
          extra_nix_config: |
            auto-optimise-store = true
            experimental-features = nix-command flakes
            download-buffer-size = 500000000 
            cores = 0  # Use all available cores
            max-jobs = auto

      - uses: cachix/cachix-action@v12
        with:
          name: rishabh5321
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build NixOS Configurations with optimized settings
        run: |
          # Use the build volume created by maximize-build-space
          export TMPDIR=/home/runner/work/dotfiles/dotfiles
          
          # Build with memory optimization flags
          nix build .#nixosConfigurations.redmi.config.system.build.toplevel \
            --option narinfo-cache-positive-ttl 0 \
            --option narinfo-cache-negative-ttl 0 \
            --option keep-going true