name: Build NixOS configs and push to Cachix

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build disk space
        uses: easimon/maximize-build-space@v10

      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            auto-optimise-store = true
            experimental-features = nix-command flakes
            download-buffer-size = 500000000
            cores = 0
            max-jobs = auto

      - name: Remount /nix to use expanded disk space
        run: |
          sudo mount --bind /home/runner/work/dotfiles/dotfiles /nix
          sudo mkdir -p /nix/store /nix/var
          sudo chown -R runner:runner /nix

      - uses: cachix/cachix-action@v12
        with:
          name: rishabh5321
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build NixOS Configurations
        run: |
          export TMPDIR=/home/runner/work/dotfiles/dotfiles/tmp
          mkdir -p "$TMPDIR"
          nix build .#nixosConfigurations.redmi.config.system.build.toplevel \
            --option keep-going true \
            --max-jobs auto
