name: Deploy GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Build site
        run: |
          mkdir docs
          cp README.md docs/index.md
      - name: Deploy to GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs
      - name: Publish
        uses: actions/deploy-pages@v4
