name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            substituters = https://cache.nixos.org https://nix-community.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Create site directory
        run: mkdir -p site

      # Create a .nojekyll file to disable Jekyll processing
      - name: Disable Jekyll
        run: touch site/.nojekyll

      # Generate system configuration documentation
      - name: Generate configuration docs
        run: |
          # Create directories
          mkdir -p site/redmi-config site/dell-config
          
          # Try to generate hardware configs (may fail in CI, so we continue anyway)
          nix-shell -p nixos-generators --run "nixos-generate-config --dir site/redmi-config --show-hardware-config" || echo "Skipping hardware config generation"
          nix-shell -p nixos-generators --run "nixos-generate-config --dir site/dell-config --show-hardware-config" || echo "Skipping hardware config generation"
          
          # Create placeholder files if hardware config generation failed
          if [ ! -f site/redmi-config/hardware-configuration.nix ]; then
            echo "# Placeholder for hardware-configuration.nix" > site/redmi-config/hardware-configuration.nix
          fi
          
          if [ ! -f site/dell-config/hardware-configuration.nix ]; then
            echo "# Placeholder for hardware-configuration.nix" > site/dell-config/hardware-configuration.nix
          fi
          
          # Create flake documentation
          echo "# Flake Inputs" > site/flake-inputs.md
          nix flake metadata --json | jq -r '.locks.nodes.root.inputs | keys[]' | sort | sed 's/^/- /' >> site/flake-inputs.md || echo "Failed to extract flake inputs"
          
          # Extract flake.nix content
          cat flake.nix > site/flake.nix

      # Create a simple index page
      - name: Create index page
        run: |
          cat > site/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>NixOS Configuration</title>
            <style>
              body {
                font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
                line-height: 1.6;
                color: #333;
                max-width: 800px;
                margin: 0 auto;
                padding: 20px;
              }
              h1 { color: #2563eb; }
              h2 { color: #4b5563; margin-top: 30px; }
              a { color: #2563eb; text-decoration: none; }
              a:hover { text-decoration: underline; }
              .config-box {
                border: 1px solid #e5e7eb;
                border-radius: 8px;
                padding: 20px;
                margin-bottom: 20px;
                box-shadow: 0 1px 3px rgba(0,0,0,0.1);
              }
              pre {
                background-color: #f5f5f5;
                padding: 10px;
                border-radius: 4px;
                overflow-x: auto;
              }
            </style>
          </head>
          <body>
            <h1>NixOS Configuration</h1>
            <p>This is the documentation for my personal NixOS configurations.</p>
            
            <div class="config-box">
              <h2>Configurations</h2>
              <ul>
                <li><a href="redmi-config/hardware-configuration.nix">Redmi Hardware Configuration</a></li>
                <li><a href="dell-config/hardware-configuration.nix">Dell Hardware Configuration</a></li>
              </ul>
            </div>
            
            <div class="config-box">
              <h2>Flake</h2>
              <ul>
                <li><a href="flake-inputs.md">Flake Inputs</a></li>
                <li><a href="flake.nix">Full flake.nix</a></li>
              </ul>
            </div>
            
            <div class="config-box">
              <h2>About</h2>
              <p>This site documents my NixOS configurations for multiple devices. The configurations are managed using a Nix Flake.</p>
            </div>
          </body>
          </html>
          EOF

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4