name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Change if your branch is different

permissions:
  contents: read
  pages: write
  id-token: write  # Required for OIDC authentication

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: github-pages  # Required for GitHub Pages deployment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install MkDocs Material
        run: pip install mkdocs-material

      - name: Build site
        run: mkdocs build -d site  # Builds the site into the "site" directory

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
