name: Sync Repository to GitLab
permissions:
  contents: read
  pull-requests: read

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to GitLab
        uses: keninkujovic/gitlab-sync@2.1.0
        with:
          gitlab_url: ${{ secrets.GITLAB_URL }}
          username: ${{ secrets.USERNAME }}
          gitlab_pat: ${{ secrets.GITLAB_PAT }}
        id: sync_step

  notify_telegram:
    runs-on: ubuntu-latest
    needs: sync
    if: always() # Ensure notification runs even on failure

    steps:
      - name: Send Telegram notification
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            *GitHub Action Notification*

            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Workflow: ${{ github.workflow }}

            *Pushed to GitLab Result*:
            ${{
              needs.sync.result == 'success' && '✅ Success' ||
              needs.sync.result == 'failure' && '❌ Failure' ||
              needs.sync.result == 'cancelled' && '🚫 Cancelled' ||
              needs.sync.result == 'skipped' && '⏭️ Skipped' ||
              '❓ Unknown' # Default case
            }}

            View Run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          format: markdown # Use markdown for formatting